- name: create aws ec2_instances and route53 records
  hosts: local
  connection: local
  vars: 
    instances: 
      - mysql 
      - backend
      - frontend
      - catalogue
      - payment
    subnet_id: subnet-0abd7aa5abe250374
    sg_id: sg-01293b21bc7d7ae0b
    zone: rshopdaws84s.site
  tasks:
  - name: create ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }} "


  - name: create r53 records for only frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }} "
    when:  item.item  == "frontend"