- name: installing based on os
  hosts: frontend
  tasks:
    - name: if os is redhat
      ansible.builtin.dnf:
      - name: nginx
        state: present
        when: ansible_os_family == RedHat

    - name: if os is debian
      ansible.builtin.apt:
      - name: nginx
        state: present
        when: ansible_os_family == Debian