- name: vars_conditions
  hosts: local
  connection: local
  # vars: 
  #   NUMBER: 70
  tasks:
    - name: printing if number is less than 100 or equal to 100
      ansible.builtin.debug:
        msg: "this number: {{ NUMBER }} is less than or equal to 100"
      when: NUMBER <= 100

    - name: printing if number is greater than 100
      ansible.builtin.debug:
        msg: "this number: {{ NUMBER }} is greater than 100"
      when: NUMBER > 100