- name: play level vars
  hosts: local
  connection: local
  tasks: 
    - name: printing the course info
      ansible.builtin.debug:
        msg: "hello from the {{ COURSE }} which has {{ DURATION }} and under the training by {{ TRAINER }}"
  
    