- name: play level vars
  hosts: local
  connection: local
  vars:
    Greetings: hi, vars of play
  vars_files:
  - course.yaml
  vars_prompt:
  - name: vars of prompt
    prompt: please enter prompt vars
    private: false
  tasks: 
    - name: printing the course info
      # vars:
      #   Greetings: hi, vars of tasks
      ansible.builtin.debug:
        msg: "hello from the {{ Greetings }}"
  
    